language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
- nightly

matrix:
  allow_failures:
  - php: hhvm
  - php: nightly

dist: trusty

install:
- composer install

before_deploy:
- tar czvf moonmoon-$TRAVIS_TAG.tgz --exclude ".git" *

# deploy:
#  provider: releases
#  skip_cleanup: true
#  file: moonmoon-$TRAVIS_TAG.tgz
#  api_key:
#    secure: CHANGE-YOUR-KEY
#  on:
#    tags: true
